apiVersion: v1
kind: Pod
metadata:
  name: bw-client
spec:
  containers:
  - name: client
    image: multi-bw:v4
    command: ["/usr/local/bin/bandwidth-checker"]
    env:
    - name: IPERF_MODE
      value: "client"
    - name: TARGET_IP
      value: "server_ip"
    - name: DURATION
      value: "10"
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  restartPolicy: Never  
