apiVersion: v1
kind: Pod
metadata:
  name: bw-server
spec:
  containers:
  - name: bw-server
    image: multi-bw:v4
    command: ["/bin/bash", "-c", "ls -l /usr/local/bin/ && /usr/local/bin/bandwidth-checker"]  
    env:
    - name: IPERF_MODE
      value: "server"
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  restartPolicy: Never

